import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import App from "../components/App.jsx";
import { Toaster } from "@/components/ui/toaster"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          {/*header*/}
          <App/>
          <main className="min-h-screen">{children}</main>
          <Toaster />
          {/*footer*/}
          <footer className="bg-muted/50 py-12">
            <div className="container mx-auto text-center px-4 text-gray-200">
              <p>Stage 2 of Task completed</p>
            </div>
          </footer>
          </ThemeProvider>
      </body>
    </html>
  );
}
